services:
  mysql:
    container_name: mysql
    build:
        context: .
        dockerfile: docker/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d/scripts
      - ./scripts/script1.sh:/docker-entrypoint-initdb.d/script1.sh
    ports:
      - 3307:3306